import React, { useState } from 'react';
import type { AppProps } from 'next/app';
import { ThemeProvider, DefaultTheme } from 'styled-components';
import Head from 'next/head';
import { Provider } from 'react-redux';
import { I18nextProvider } from 'react-i18next';
import { Backdrop, CircularProgress } from '@mui/material';

import { FooterLayout, HeaderLayout } from '@/src/layouts';
import ContentLayout from '@/src/layouts/content';
import { store } from '@/src/stores';
import { I18n } from '@/src/configs/i18n/i18n';

import GlobalStyle from '@/src/assets/styles/globalstyles';

const theme: DefaultTheme = {
  colors: {
    primary: '#111',
    secondary: '#0070f3',
  },
};

const App: React.FC<AppProps> = ({ Component, pageProps }: AppProps) => {
  const [isLoading, setIsLoading] = useState(true);

  setTimeout(() => {
    setIsLoading(false);
  }, 1000);

  return (
    <>
      <Head>
        <title>Nha khoa Đại Việt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Provider store={store}>
        <I18nextProvider i18n={I18n}>
          <ThemeProvider theme={theme}>
            <GlobalStyle />

            {isLoading ? (
              <Backdrop sx={{ color: '#fff', zIndex: theme => theme.zIndex.drawer + 1 }} open={isLoading}>
                <CircularProgress color="inherit" />
              </Backdrop>
            ) : (
              <>
                <HeaderLayout />

                <ContentLayout>
                  <Component {...pageProps} />
                </ContentLayout>

                <FooterLayout />
              </>
            )}
          </ThemeProvider>
        </I18nextProvider>
      </Provider>
    </>
  );
};

export default App;
